logo: "https://github.com/evanca/evanca.github.io/blob/master/logo.png?raw=true"
description: > # newlines will be ignored in this theme, using <br> instead
  Hi, I am Ivanna, a software-engineering enthusiast with a business background. I have over 10 years' expertise in the promotional product (aka. "merch", "swag") field, and 2+ years of software development experience, ever since I have won my first tech scholarship.
  <br><br>
  <a href="https://www.linkedin.com/in/acevica/">View My LinkedIn Profile</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-134454667-1
